# This is about basic NumPy and Vectorization

In [1]:
import numpy as np
import time

Creation of Numpy array with random and zero values

In [2]:
a=np.zeros(4)
print(f"a={a} shape is {a.shape} and data type is {a.dtype}")

b=np.zeros(4,)
print(f"b={b} shape is {b.shape} and data type is {b.dtype}")

c=np.random.rand(4,2)
print(f"c={c} shape is {c.shape} and data type is {c.dtype}")

a=[0. 0. 0. 0.] shape is (4,) and data type is float64
b=[0. 0. 0. 0.] shape is (4,) and data type is float64
c=[[0.62581877 0.69009524]
 [0.87984561 0.03797035]
 [0.58753236 0.78857541]
 [0.72861512 0.17446487]] shape is (4, 2) and data type is float64


Creation of array using range function to be in specific range

In [3]:
a=np.arange(5,15,2)
print(f"a={a}")

a=[ 5  7  9 11 13]


In [4]:
a=np.array([5.,1,2,30])
print(f"a={a} shape is {a.shape} and data type is {a.dtype}")

a=[ 5.  1.  2. 30.] shape is (4,) and data type is float64


so even if one element is floating point value the entire array is floating point values

# Indexing

Indexing in python starts with 0

In [5]:
a=np.arange(10)
print(a)

# To acess the elements we use the index
print(f"a[2].shape={a[2].shape} and a2={a[2]}")

# To get or acess the last element we use index as -1
print(f"a[-1]={a[-1]}")

# We can only acess those elements which are within the range 
# here the last element index is 9 so even if we use 10 it will throw error
try:
    c=a[10]
except Exception as e:
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape=() and a2=2
a[-1]=9
index 10 is out of bounds for axis 0 with size 10


# Slicing

In [6]:
a=np.arange(10)
print(a)
print(f"a[2:7:1]={a[2:7:1]}")
print(f"a[2:7:2]={a[2:7:2]}")
print(f"a[3:]={a[3:]}")
print(f"a[:3]={a[:3]}")
print(f"a[:]={a[:]}")

[0 1 2 3 4 5 6 7 8 9]
a[2:7:1]=[2 3 4 5 6]
a[2:7:2]=[2 4 6]
a[3:]=[3 4 5 6 7 8 9]
a[:3]=[0 1 2]
a[:]=[0 1 2 3 4 5 6 7 8 9]


# Single Vector Operations

In [7]:
a=np.array([1,2,3,4])
print(f"a={a}")
print(f"-a={-a}")
print(f"np.sum(a)={np.sum(a)}")
print(f"np.mean(a)={np.mean(a)}")
print(f"a**2={a**2}")

a=[1 2 3 4]
-a=[-1 -2 -3 -4]
np.sum(a)=10
np.mean(a)=2.5
a**2=[ 1  4  9 16]


# Vector-Vector Element wise operation

We can add and subtract the vectors only of same order

In [8]:
a=np.array([1,2,3,4])
b=np.array([-1,-2,3,4])
print(f"Binary operator works element wise a+b={a+b}")

Binary operator works element wise a+b=[0 0 6 8]


In [10]:
# We cannot add/subtract vectors with different order
c=np.array([1,2])
try:
    d=c+a
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (4,) 


# Scalar Vector Operations 

In [11]:
a=np.array([1,2,3,4])
print(f"5*a={5*a}")

5*a=[ 5 10 15 20]


# Dot Product

(i) Using For Loop

In [12]:
def dot(a,b):
    s=0
    for i in range(a.shape[0]):
        s=s+a[i]*b[i]
    return s

In [13]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
print(f"a.b={dot(a,b)}")

a.b=20


dot product is commutative meaning a.b=b.a 

Also to note that the shape of a scalar value is empty () Eg: dt products shape

# Time Comparision between Vector method and Loop method

In [21]:
# Lets take huge arrays for comparision
a=np.random.rand(100000)
b=np.random.rand(100000)

# 1. Using Vector method
tic=time.time()  # Start time
c=np.dot(a,b)
toc=time.time()  # Stop time

print(f"Dot product is {c:.4f}")
print(f"The time taken by vectorization is {1000*(toc-tic):.4f} ms")
# We can even use @ for dot product

# 2. Using Loop method
tic=time.time()
c=dot(a,b)
toc=time.time()
print(f"Dot product is {c:.4f}")
print(f"The time taken by Loop method is {1000*(toc-tic):.4f} ms")

Dot product is 25104.5636
The time taken by vectorization is 1.0192 ms
Dot product is 25104.5636
The time taken by Loop method is 29.8972 ms


# Matrix Creation 

For creating matrices with random zero and ones we will use (shape) inside the function parameters

In [24]:
a=np.zeros((2,1))
print(f"a.shape={a.shape} and a={a}")

b=np.ones((1,5))
print(f"b.shape={b.shape} and b={b}")

c=np.random.random_sample((4,2))
print(f"c.shape={c.shape} and c={c}")

a.shape=(2, 1) and a=[[0.]
 [0.]]
b.shape=(1, 5) and b=[[1. 1. 1. 1. 1.]]
c.shape=(4, 2) and c=[[0.97910411 0.00475782]
 [0.7886788  0.82943347]
 [0.28204832 0.45017137]
 [0.84060644 0.70121617]]


# Matrix Indexing

In [29]:
a=np.array([[1,2,3],[4,5,6]])
print(f"a[0,1]={a[0,1]}") # acess an element
print(f"a[1]={a[1]}")     # acess a row
print(f"a.reshape(3,2):{a.reshape(3,2)}")  #Reshaping

a[0,1]=2
a[1]=[4 5 6]
a.reshape(3,2):[[1 2]
 [3 4]
 [5 6]]


# Matrix Slicing 

In [31]:
a=np.arange(20)
a=a.reshape(-1,10)
# here -1 is used to auto fill the required shape value
print(f"a={a}")
print(f"a[0,2:7:1]={a[0,2:7:1]}") # accessing elements in one row
print(f"a[:,2:7:1]={a[:,2:7:1]}") # accessing elements in all rows
print(f"a[:,:]={a[:,:]}")         # accessing all elements
print(f"a[1,:]={a[1,:]}")         # accessing all elements in one row
# both are same
print(f"a[1]={a[1]}")
print(f"a[0:2,2:8:2]={a[0:2,2:8:2]}")


a=[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0,2:7:1]=[2 3 4 5 6]
a[:,2:7:1]=[[ 2  3  4  5  6]
 [12 13 14 15 16]]
a[:,:]=[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[1,:]=[10 11 12 13 14 15 16 17 18 19]
a[1]=[10 11 12 13 14 15 16 17 18 19]
a[0:2,2:8:2]=[[ 2  4  6]
 [12 14 16]]
