# Simple Neural networks

Linear and Logistic Regression implementation using Tensorflow
and Some simple Neural network creation using tensorflow

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError,BinaryCrossentropy
from tensorflow.keras.activations import sigmoid

## Neuron without activation - Regression/Linear Model

Building a Linear Regression model using neurons

We are building the same housing price prediction model of lab1 

In [2]:
x_train = np.array([[1.0],[2.0]],dtype = np.float32)
y_train = np.array([[300.0],[500.0]],dtype = np.float32)
print(f" x_train={x_train}\n y_train={y_train}")

 x_train=[[1.]
 [2.]]
 y_train=[[300.]
 [500.]]


In [3]:
linear_layer = tf.keras.layers.Dense(1,activation = 'linear')

In [4]:
print(linear_layer)

In [5]:
linear_layer.get_weights()

[]

if we try to get weights from the above model it will be empty because we have not provided with input layer

There are no weights as the weights are not yet instantiated. Let's try the model on one example in `X_train`. This will trigger the instantiation of the weights. Note, the input to the layer must be 2-D, so we'll reshape it.

In [6]:
a1 = linear_layer(x_train[0].reshape(1,1))
print(a1)

tf.Tensor([[0.53825676]], shape=(1, 1), dtype=float32)


here we are applying one row as input to neural network to initalize weights

The result is a tensor (another name for an array) with a shape of (1,1) or one entry.   
Now let's look at the weights and bias. These weights are randomly initialized to small numbers and the bias defaults to being initialized to zero.

In [7]:
w,b=linear_layer.get_weights()
print(f"w={w} and b={b}")

w=[[0.53825676]] and b=[0.]


A linear regression model (1) with a single input feature will have a single weight and bias. This matches the dimensions of our `linear_layer` above.   

The weights are initialized to random values so let's set them to some known values.

In [8]:
set_w = np.array([[200]])
set_b = np.array([100])

linear_layer.set_weights([set_w,set_b])
print(linear_layer.get_weights())

[array([[200.]], dtype=float32), array([100.], dtype=float32)]


predicting the output house price for x_train[0]

In [9]:
a1 = linear_layer(x_train[0].reshape(1,1))
print(a1)

alin = np.dot(set_w,x_train[0])+set_b
print(alin)

tf.Tensor([[300.]], shape=(1, 1), dtype=float32)
[300.]


Predicting x_train

In [10]:
prediction_tf = linear_layer(x_train)
prediction_np = np.dot(x_train,set_w)+set_b
print(f"Prediction using tensorflow \n{prediction_tf}")
print(f"Prediction using numpy \n{prediction_np}")

Prediction using tensorflow 
[[300.]
 [500.]]
Prediction using numpy 
[[300.]
 [500.]]


## Logistic Regression using the neurons and neural network Architecture

We are using the same example of Logistic Regression which we had used before

In [11]:
x_train = np.array([0.,1,2,3,4,5],dtype=np.float32).reshape(-1,1)
y_train = np.array([0,0,0,1,1,1],dtype=np.float32).reshape(-1,1)
print(f" x_train = \n{x_train}\n y_train = \n{y_train}")

 x_train = 
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]
 y_train = 
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]


### Logistic Neuron
We can implement a 'logistic neuron' by adding a sigmoid activation.    
This section will create a Tensorflow Model that contains our logistic layer to demonstrate an alternate method of creating models. Tensorflow is most often used to create multi-layer models. The [Sequential](https://keras.io/guides/sequential_model/) model is a convenient means of constructing these models.

In [12]:
model = Sequential(
[
    tf.keras.layers.Dense(1,input_dim=1,activation='sigmoid',name='L1')
])

Here we are building the model by passing input_dim=1

`model.summary()` shows the layers and number of parameters in the model. There is only one layer in this model and that layer has only one unit. The unit has two parameters, $w$ and $b$.

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


here param represents the parameters w and b

In [14]:
Logistic_layer = model.get_layer('L1')
w,b = Logistic_layer.get_weights()
print(f"w={w} and b={b}")
print(f"w.shape={w.shape} and b.shape={b.shape}")

w=[[-0.87320167]] and b=[0.]
w.shape=(1, 1) and b.shape=(1,)


Similar to linear regression here the weights will be set to some value and b as 0, when given some input(i.e the weights which we get by initalizing is not the optimal weights which we require) if we dont initialize the model by passing input then it will give empty set of weights and bias

Let's set the weight and bias to some known values.

In [15]:
set_w = np.array([[2]])
set_b = np.array([-4.5])
Logistic_layer.set_weights([set_w,set_b]) 
w,b = Logistic_layer.get_weights()
print(f"w={w} and b={b}")

w=[[2.]] and b=[-4.5]


Lets predict using this model

In [16]:
a1 = model.predict(x_train[0].reshape(1,1))
print(a1)

1/1 [==============================] - 0s 156ms/step
[[0.01098694]]


In [17]:
alog = (np.dot(set_w,x_train[0])+set_b)
a1 = 1/(1+np.exp(-alog))
print(a1)

[0.01098694]


In [24]:
a1=model.predict(x_train)
print(a1)

num=x_train.shape[0]
a_out=np.zeros(num)
for i in range(num):
    if a1[i]>=0.5:
        a_out[i]=1
    else:
        a_out[i]=0
print("\n",a_out)

1/1 [==============================] - 0s 5ms/step
[[0.01098694]
 [0.07585818]
 [0.37754068]
 [0.8175745 ]
 [0.97068775]
 [0.99592984]]

 [0. 0. 0. 1. 1. 1.]


Thus we built the Linear and Logistic Regression models using Tensorflow neuron architecture